### PR TITLE
New Name

### PR DESCRIPTION
**Pull request by bastianallgeier**

### CODE REVIEW

**Comment by distantnative** [comment]
:+1:

**Comment by displayn** [comment]
:hear_no_evil:

**Comment by lukasbestle** [comment]
Sounds great! :+1:

**Comment by sebastianrakel** [comment]
:+1:

**Comment by stereonom** [comment]
:+1:

**Comment by tbreuss** [comment]
?

**Comment by tbreuss** [comment]
:-1:

**Comment by distantnative** [comment]
I was so sure you would accept this much more creative name suggestion.

**Comment by tbreuss** [comment]
Well, I have to think about it. My project startet really small. The name was chosen within a blink of an eye (two years ago)...

**Comment by lukasbestle** [comment]
The story about this PR started on [Twitter](https://twitter.com/bastianallgeier/status/643371633214902272) today, as Herbie and Kirby are quite similar names, have similar logos and domains and are a similar type of software.

**Comment by visualcookie** [comment]
If you notice the PR right... the renaming is basically referring to Jekyll. :stuck_out_tongue:

**Comment by bastianallgeier** [comment]
I'm normally very relaxed about such stuff. Taking inspiration from somewhere is often an important step to come up with something on your own. Also everyone is of course free to build their own CMS, file-based or not. But you even listen Kirby as inspiration on your site. Kirby has been around for more than 3,5 years and thousands of hours have went into the system as well as the branding, building the community and much more. 90% of my income is currently generated by Kirby, so my Family and I heavily depend on it. Coming up with a name that is so extremely close to what I've created over years for a product that is even closer is just not ok. Even the logo with the E instead of the K and the red background and the slogan "handmade with Herbie" seem almost like some kind of bad joke towards Kirby. Many people recognized this instantly on Twitter. Just do yourself a favor and come up with something more unique. I don't mean this as some sort of stupid threat but really more like an advice. If you take your project seriously you are better off when you build something for yourself which your community can relate to later and that doesn't feel like a weak copy of a product that already exists. I believe that there's enough space on the web for many many systems with different directions, just as long as we don't cross some very basic borders of fairness. 

This PR was of course not very professional and I apologize for that. I just had to turn it into a little fun thing and I hope you don't take it personal :)

All the best, 
Bastian (Kirby)

**Comment by tbreuss** [comment]
@bastianallgeier Aren't you overdoing a little? 

As I wrote yesterday I will consider changing the name but not today and not tomorrow. Although I do not see much similarity between the logos I will also consider changing it. You have certainly realized that it is in fact no logo but simply some colored markup? And I will also consider changing "Handgemacht mit Herbie". Although I could find thousands of websites using this slogan I'm sure you have some kind of "trademark" on this. I will also consider changing "getxyz.org" although it is not unusual to use such names (see: https://getcomposer.org, http://getgrav.org, etc). Again, I'm quite sure you have some trademark on this too.

Your reaction was in fact not really professional. You are bashing a project on Twitter that comes with a handful of installations world wide? Needless to say that most of them are mine. At the same time you are worrying about your income and family. 

Let me give an advice to you too: You better focus your energy and bring your (undoubted) great CMS one step further. Otherwise the new kids on the block and your real competitors like https://getgrav.org or https://statamic.com will overtake you in a minimum of time.

**Comment by distantnative** [comment]
Classy.

**Comment by tbreuss** [comment]
@bastianallgeier Lol. Seven years old and still good!

**Pull request closed without merging**
